spring:
  application:
    name: eureka-consumer-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
server:
  port: 8989
management:
  endpoints:
    web:
      exposure:
        include: "*"