server:
  port: 7003 #端口

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:7002/eureka/,http://peer3:7003/eureka/  #設置與Eureka Server交行的地址查詢服務和註冊服務
