server:
  port: 7000 #端口

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer1 #eureka服務端的實例名
  client:
    registerWithEureka: true #false表示不向註冊中心註冊自己
    fetch-registry: true #false表示自己就是註冊中心，我的職責是維護服務實例，並不需要去檢索服務。
    serviceUrl:
      defaultZone: http://peer2:7002/eureka/,http://peer3:7003/eureka/  #設置與Eureka Server交行的地址查詢服務和註冊服務